http:
  routers:
    apache-airflow-router:
      rule: "Host(`apache-airflow.valuechainhackers.xyz`)"
      service: apache-airflow-service
      entryPoints:
        - web
  services:
    apache-airflow-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.13:8080"
