http:
  routers:
    crawlai-router:
      rule: "Host(`crawlai.valuechainhackers.xyz`)"
      service: crawlai-service
      entryPoints:
        - web
  services:
    crawlai-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.23:8080"
