http:
  routers:
    jaamsim-router:
      rule: "Host(`jaamsim.valuechainhackers.xyz`)"
      service: jaamsim-service
      entryPoints:
        - web
  services:
    jaamsim-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.35:8080"
