http:
  routers:
    kile-router:
      rule: "Host(`kile.valuechainhackers.xyz`)"
      service: kile-service
      entryPoints:
        - web
  services:
    kile-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.36:8080"
