http:
  routers:
    kmplot-router:
      rule: "Host(`kmplot.valuechainhackers.xyz`)"
      service: kmplot-service
      entryPoints:
        - web
  services:
    kmplot-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.37:8080"
