http:
  routers:
    knime-router:
      rule: "Host(`knime.valuechainhackers.xyz`)"
      service: knime-service
      entryPoints:
        - web
  services:
    knime-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.38:8080"
