http:
  routers:
    lychee-router:
      rule: "Host(`lychee.valuechainhackers.xyz`)"
      service: lychee-service
      entryPoints:
        - web
  services:
    lychee-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.44:8080"
