http:
  routers:
    mattermost-router:
      rule: "Host(`mattermost.valuechainhackers.xyz`)"
      service: mattermost-service
      entryPoints:
        - web
  services:
    mattermost-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.46:8065"
