http:
  routers:
    minio-router:
      rule: "Host(`minio.valuechainhackers.xyz`)"
      service: minio-service
      entryPoints:
        - web
  services:
    minio-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.48:9000"
