http:
  routers:
    modoboa-router:
      rule: "Host(`modoboa.valuechainhackers.xyz`)"
      service: modoboa-service
      entryPoints:
        - web
  services:
    modoboa-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.49:8080"
