http:
  routers:
    nginxproxymanager-router:
      rule: "Host(`nginxproxymanager.valuechainhackers.xyz`)"
      service: nginxproxymanager-service
      entryPoints:
        - web
  services:
    nginxproxymanager-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.51:8080"
