http:
  routers:
    photoprism-router:
      rule: "Host(`photoprism.valuechainhackers.xyz`)"
      service: photoprism-service
      entryPoints:
        - web
  services:
    photoprism-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.56:8080"
