http:
  routers:
    prometheus-router:
      rule: "Host(`prometheus.valuechainhackers.xyz`)"
      service: prometheus-service
      entryPoints:
        - web
  services:
    prometheus-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.59:9090"
