http:
  routers:
    radarr-router:
      rule: "Host(`radarr.valuechainhackers.xyz`)"
      service: radarr-service
      entryPoints:
        - web
  services:
    radarr-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.61:7878"
