http:
  routers:
    rocketchat-router:
      rule: "Host(`rocketchat.valuechainhackers.xyz`)"
      service: rocketchat-service
      entryPoints:
        - web
  services:
    rocketchat-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.66:3000"
