http:
  routers:
    runescape-router:
      rule: "Host(`runescape.valuechainhackers.xyz`)"
      service: runescape-service
      entryPoints:
        - web
  services:
    runescape-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.67:8080"
