http:
  routers:
    sanic-router:
      rule: "Host(`sanic.valuechainhackers.xyz`)"
      service: sanic-service
      entryPoints:
        - web
  services:
    sanic-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.69:8000"
