http:
  routers:
    service3-router:
      rule: "Host(`service3.test`)"
      service: service3-service
      entryPoints:
        - web
  services:
    service3-service:
      loadBalancer:
        servers:
- url: "http://10.0.6.12:8080"
