http:
  routers:
    shelfie-router:
      rule: "Host(`shelfie.valuechainhackers.xyz`)"
      service: shelfie-service
      entryPoints:
        - web
  services:
    shelfie-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.72:8000"
