http:
  routers:
    syncthing-router:
      rule: "Host(`syncthing.valuechainhackers.xyz`)"
      service: syncthing-service
      entryPoints:
        - web
  services:
    syncthing-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.76:8384"
