http:
  routers:
    traefik-router:
      rule: "Host(`traefik.valuechainhackers.xyz`)"
      service: traefik-service
      entryPoints:
        - web
  services:
    traefik-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.84:8080"
