http:
  routers:
    truecharts-router:
      rule: "Host(`truecharts.valuechainhackers.xyz`)"
      service: truecharts-service
      entryPoints:
        - websecure
  services:
    truecharts-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.89:80"
