http:
  routers:
    uptimekuma-router:
      rule: "Host(`uptimekuma.valuechainhackers.xyz`)"
      service: uptimekuma-service
      entryPoints:
        - websecure
  services:
    uptimekuma-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.90:80"
