http:
  routers:
    vikunja-router:
      rule: "Host(`vikunja.valuechainhackers.xyz`)"
      service: vikunja-service
      entryPoints:
        - websecure
  services:
    vikunja-service:
      loadBalancer:
        servers:
          - url: "http://10.0.6.92:80"
