version: "3.9"

services:
  ortools:
    image: ortools/ortools:latest
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.ortools.rule=Host(`ortools.localhost`)"
      - "traefik.http.routers.ortools.entrypoints=websecure"
      - "traefik.http.routers.ortools.tls.certresolver=myresolver"
