version: "3.9"

services:
  jupyterhub:
    image: jupyterhub/jupyterhub:latest
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - jupyterhub_data:/srv/jupyterhub
    environment:
      POSTGRES_HOST: db
      POSTGRES_USER: your_user
      POSTGRES_PASSWORD: your_password
      POSTGRES_DB: your_database
    depends_on:
      - db

volumes:
  jupyterhub_data:
