version: "3.9"
services:
  ortools:
    image: python:3.9-slim-buster
    restart: unless-stopped
    volumes:
      - ./ortools_code:/app
    working_dir: /app
    command: ["python", "your_script.py"] # Replace with your script
