---
- hosts: all
  become: true
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      when: ansible_os_family == "Debian"

    - name: Install Docker Compose
      apt:
        name: docker-compose
        state: present
      when: ansible_os_family == "Debian"

    - name: Clone application repository
      git:
        repo: your_git_repository_url
        dest: /opt/your_application
        version: main

    - name: Deploy Docker Compose
      command: docker-compose up -d
      chdir: /opt/your_application
